"""add composite indexes on transactions

Revision ID: b97ee9249328
Revises: 62d3c59767fa
Create Date: 2026-09-09 19:19:34.846865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97ee9249328'
down_revision = '62d3c59767fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transactions_status_date', ['status', 'transaction_date'], unique=False)
        batch_op.create_index('idx_transactions_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_transactions_user_status')
        batch_op.drop_index('idx_transactions_status_date')

    # ### end Alembic commands ###
