"""Added user profile settings

Revision ID: bb68a30aee7a
Revises: e5835b801cea
Create Date: 2026-07-22 10:34:40.137965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'bb68a30aee7a'
down_revision = 'e5835b801cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notification_preferences', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notification_preferences')
        batch_op.drop_column('location')
        batch_op.drop_column('phone')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('department')
        batch_op.drop_column('organization')

    # ### end Alembic commands ###
